Added test report generator

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -33,7 +33,7 @@ jobs:
         name: Generate snapshot version
         shell: bash
         run: |
-          version=$(git describe --tag --abbrev=0 | cut -c 2- || echo 0.1.0)
+          version=$(git describe --tag --abbrev=0 || echo "v0.1.0" | cut -c 2-)
           regex="^([0-9]+).([0-9]+).([0-9]+)$"
           if [[ $version =~ $regex ]]; then
             major="${BASH_REMATCH[1]}"
@@ -57,6 +57,12 @@ jobs:
 
       - name: Build
         run: ./gradlew -Pversion=${{ steps.get_version.outputs.version }} build
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: always() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
 
       - name: Upload SNAPSHOT artifacts to Sonatype
         id: upload_release_artifacts
